echo [build] > netlify.toml
echo   command = "npx expo export --platform web" >> netlify.toml
echo   publish = "web-build" >> netlify.toml
echo. >> netlify.toml
echo [[redirects]] >> netlify.toml
echo   from = "/*" >> netlify.toml
echo   to = "/index.html" >> netlify.toml
echo   status = 200 >> netlify.toml